- name: copy racoon public keys 
  copy: src={{ item }} dest=/etc/racoon/certs/ owner=root mode=600
  with_fileglob:
    - "files/etc/racoon/certs/*.pub"
- name: create ipsec.yaml
  become: false
  script: scripts/make_ipsec_yaml.py config
  delegate_to: localhost
- name: create racoon config
  become: false
  script: scripts/make_ipsec_yaml.py config
  delegate_to: localhost
- name: copy ip_addresses.yaml 
  copy: src=config/ip_addresses.yaml dest=/home/vagrant/ip_addresses.yaml
- name: create racoon configuration files 
  script: scripts/create_config.py {{ host_name }} /home/vagrant/ip_addresses.yaml
#- name: copy setkey configuration files 
#  copy: src={{ item }} dest=/etc/ owner=root 
#  with_items:
#    - "{{ files_root }}/files/{{ host_name }}/etc/ipsec-tools.conf"
#  notify:
#    - restart setkey
#- name: copy ipsec racoon.conf
#  copy: src={{ files_root }}/files/{{ host_name }}/etc/racoon/racoon.conf dest=/etc/racoon/racoon.conf
#  notify:
#    - restart racoon

