---
- name: create key
  include: tasks/create_key.yaml
  when: create_key is defined and create_key == "True"
#- name: create configuration
#  include: tasks/create_conf.yaml
#  when: create_conf is defined and create_conf == "True"
